= Алгоритм работы Привычек

== Сущности
Имеются 2 сущности:
- Привычка
- Факт привычки

=== Привычка
Сущность "Привычка" имеет следующие свойства:
- id. Автогенерация.
- Название. Текст до 40 символов. Обязательное.
- Иконка. Конечное множество, характеризующееся 7-ю иконками. Условно: "бег", "чтение", "медитация", "вода", "теннис", "баскетбол", "футбол". Обязательное.
- Цвет. Конечное множество из 7 цветов, как в макете.
- Недельная периодичность. Булевый вектор длиной 7, соответствующий дням недели.
- Статус заморозки. Булевый. По умолчанию false. В этом статусе могут находиться не более 3-х привычек.

В приложении хранится список созданных пользователем привычек.

=== Факт привычки
При запуске приложения проверяется наличие фактов привычек на текущую дату. Если фактов нет, то проверяется
наличие созданных привычек для текущего дня недели. Если такие есть, то создаются соответствующие факты привычек
со значением текущей даты, id привычки и с полем выполнения false.

Сущность "Факт привычки" имеет следующие свойства:
- Дата.
- id привычки.
- Факт выполнения. Булевый. По умолчанию false.

== Функционал экранов

=== Список даты
Отображается список фактов привычек, соответствующих выбранной дате (текущей по умолчанию). Элемент списка отображает
характеристики привычки, которая соотнесена с фактом, и статус факта выполнения. При нажатии на элемент происходит
переход на экран управления привычкой. Если экран отображает список для текущего дня, чекбокс статуса активен и
пользователь может переключать статус. Для других дней прошлого и будущего чекбоксы неактивны. Если отображается экран
для прошедших дат, то список фактов берется из созданных и сохраненных. Для дат в будущем отображается список "пустых"
фактов для дня недели этой даты. При нажатии на "+" происходит переход на экран создания новой привычки.

=== Создание привычки
Пользователь заполняет свойства новой привычки и создает ее. Если выбрана опция "Ежедневно", то это эквивалентно тому,
что в опции "По дням недели" выбраны все дни. По кнопке "Назад" происходит переход на список привычек текущего дня.
Функция "Напоминание" на данном этапе отключена.

=== Управление привычкой
Имеет функционал изменения имени привычки и статуса заморозки с проверкой допустимости этой опции. Отображается статистика
привычки:
- "Текущая" — общее кол-во созданных фактов этой привычки.
- "Лучшая" — ПОКА НЕ ЯСНО!
- "За 30 дней" — кол-во созданных фактов этой привычки за 30 дней.

==== Тепловая карта
Отображается текущая неделя, в котором отмечены дни с этой привычкой. НЕ ЯСНО!

==== Выполнение по дням недели
Отображается максимальный процент задействованной привычки за неделю (день недели?). ПОКА НЕ ЯСНО!

==== Кнопка заморозки
Если не превышен лимит, то кнопка активна и по нажатию устанавливается статус заморозки. Нет функционала разморозки.
Добавлю опцию.
