= Бизнес-требования статистики привычек

== 1. Интерфейс

=== 1.1. Первая секция "Заголовок"
Состоит из иконки привычки, названия и кнопки редактирования. По нажатию на эту кнопку поле "название" становится
редактируемым, а иконка меняется на зеленую галочку "ОК". При нажатии на нее название сохраняется и поле "название"
становится текстом.

=== 1.2. Вторая секция "Количество"
Состоит из трех статистических показателей привычки: "Текущая", "Лучшая", "За 30 дней". Правила расчета:

* "Текущая". Количество true фактов (`isCompleted`) этой привычки без пропусков - если пользователь в какой-то из дней,
где эта привычка активна, не отметил её, счётчик сбрасывается в 0 и со следующего факта проставления (`isCompleted`)
начинается заново.
* "Лучшая". Лучший результат без пропусков. Если текущий результат является по совместительству лучшим — значит у них
одинаковые значения.
* "За 30 дней". Процент успешности — т.е. количество true фактов (`isCompleted`) разделённое на общее количество дней
(и с true и, с false фактом) этой привычки за последние 30 дней.

